### ISSUE TITLE
corruption softlocks game

### ISSUE THREAD

**Issue by Hammerkirby123** [ImKyle4815/ArtifactEnsemble#6] opened 2022-03-22 20:12 UTC
with artifact of corruption, after i beat the second wave, the lunar pods don't spawn and the next wave doesn't start
![image](https://user-images.githubusercontent.com/101952935/159567123-4231409f-86bc-4a15-b5ad-1d4892654c15.png)
the error
![image](https://user-images.githubusercontent.com/101952935/159567361-605b860f-7613-4f25-9d70-7742d15f2f23.png)
![image](https://user-images.githubusercontent.com/101952935/159567419-bcf6280c-aa47-480a-835d-6b52711c97df.png)
![image](https://user-images.githubusercontent.com/101952935/159567453-2e3caa6a-136e-4093-b0c1-24a0fc42f17a.png)
![image](https://user-images.githubusercontent.com/101952935/159567480-d52a6260-9c07-4477-949b-701dbd7e6da1.png)
![image](https://user-images.githubusercontent.com/101952935/159567508-65d2ff98-9b4b-4586-aecc-860b9211f40f.png)
my mod list (i know i have a lot)

**Comment by oorzkws** [comment] 2022-03-23 02:12
Seems to be caused by Sacrifice also being active.

**Comment by Hammerkirby123** [comment] 2022-03-23 03:05
Darn, is there a way for the creator to fix it?

**Comment by oorzkws** [comment] 2022-03-23 04:00
> Darn, is there a way for the creator to fix it?

He can merge my changes and upload to thunderstore. If you feel so inclined you can replace your local copy with the copy from the attached zip.
![image](https://user-images.githubusercontent.com/65210810/159621250-2d25a96d-ea2b-458d-9ff6-2367c750eb07.png)
-> `BepInEx/plugins/ImKyle4815-ArtifactEnsemble`
[ArtifactEnsemble.zip](https://github.com/ImKyle4815/ArtifactEnsemble/files/8329587/ArtifactEnsemble.zip)

**Comment by oorzkws** [comment] 2022-03-28 23:30
Resolved in #7

**Closed as completed** 2022-03-29 03:36 UTC
